apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::561404573839:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-L9n2dshbwHlJ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-22T12:53:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1699"
  uid: 83937e20-c7a4-42ac-9528-067bcfa1822b
