apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::561404573839:role/codebuild-eks-devops-build-551-service-role
      username: build
      groups:
        - system:masters
    - rolearn: arn:aws:iam::561404573839:role/eksctl-eksdemo1-nodegroup-eksdemo1-NodeInstanceRole-L9n2dshbwHlJ
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes

kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::561404573839:role/codebuild-eks-devops-build-551-service-role\n  username: build\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2025-05-22T12:53:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "23421"
  uid: 83937e20-c7a4-42ac-9528-067bcfa1822b
